
int Solve_UP_JH_Interval(int Degree,VECTOR &Coeff,
		INTERVAL & TheDomain, 
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			 int Nb_Max_Solution);
int Solve_UP_JH_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
int Solve_UP_JH_Positive_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
int Solve_UP_JH_Negative_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
int Fast_Solve_UP_JH_Interval(int Degree,VECTOR &Coeff,
		INTERVAL & TheDomain, 
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kantos,
			      int Nb_Max_Solution);
int Fast_Solve_UP_JH_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
int Fast_Solve_UP_JH_Positive_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
int Fast_Solve_UP_JH_Negative_Interval(int Degree,VECTOR Coeff,
		int Order,
		int Iteration,
		int Stop_First_Sol,
		double Accuracy_Variable,
		double Accuracy,
		INTERVAL_VECTOR & Solution,
                INTEGER_VECTOR & Is_Kanto,
			      int Nb_Max_Solution);
extern INTERVAL_VECTOR Interval_Solution_UP;
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int *Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Solve_Poly)(double *, int *,double *), 
			     int (* Simp_Proc)(INTERVAL_VECTOR &));

int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Solve_Poly)(double *, int *,double *), 
			     int (* Simp_Proc)(INTERVAL_VECTOR &));

int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place);
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_EigenValues(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,
			     int Use_Solve,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_EigenValues_Area(int Degree,  
			     int Nb_Parameter,
			     int Has_Interval,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
	  INTERVAL_VECTOR (* TheCoeffCentered)(INTERVAL_VECTOR &,double), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int *Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			      int Nb_Points,
			     int Use_Solve,
			     int rand_max,
			     int Strong,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     double AccuracyB,
			     double *Volume_Result,
			     double *Volume_Neglected,
			     double *Seuil_First_Sol1,
			     int Stop_First_Sol,
			     char *FileName,
			     int Has_Input,
			     char *File_Input,
			     int (* Solve_Poly)(double *, int *,double *), 
			     int RealRoot,
	  INTERVAL_VECTOR (* Evaluate_Complex)(int,int,INTERVAL_VECTOR &), 
			     int (* Simp_Proc)(INTERVAL_VECTOR &));

int ALIAS_Solve_Poly(double *C,int *n,double *sol);
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute1,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Solve_Poly)(double *, int *,double *), 
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place);
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol,
			     int (* Simp_Proc)(INTERVAL_VECTOR &));
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Min_Max_CN(int Degree,  
			     int Nb_Parameter,
	  INTERVAL_VECTOR (* TheCoeff)(INTERVAL_VECTOR &), 
			     int Nb_Constraints,
			     INTEGER_VECTOR &Type_Eq,
	  int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
	  int Has_Matrix,
	  INTERVAL_VECTOR (* TheIntervalFunction)(int,int,INTERVAL_VECTOR &), 
	  int Has_Gradient,
          INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			     INTERVAL & TheDomain, 
			     INTERVAL_VECTOR & TheDomain_Parameter, 
			     int Type,
			      int Nb_Points,int Absolute,
			      int rand_max,
			     int Iteration,
			     double Accuracy_Variable,
			     double Accuracy,
			     double AccuracyM,
			     INTERVAL &Lowest_Root,
			     INTERVAL &Highest_Root,
			     INTERVAL_MATRIX &Place,
			     int  Stop_First_Sol,
			     double *Seuil_First_Sol);
int ALIAS_Geometry_Carre(int Degree,  
			 int Nb_Parameter,
			 INTERVAL_VECTOR (* TheCoeff)
			 (INTERVAL_VECTOR &), 
			 int Nb_Constraints,
			 INTEGER_VECTOR &Type_Eq1,
			 INTEGER_VECTOR &Imperatif1,	
			 int (* TheMatrix)(INTERVAL_VECTOR &, INTERVAL_MATRIX &), 
			 int Has_Matrix,
			 INTERVAL_VECTOR (* F)(int,int,INTERVAL_VECTOR &),  
			 int *Has_Gradient,
			 INTERVAL_MATRIX (* Gradient)(int, int,INTERVAL_VECTOR &), 
			 INTERVAL & TheDomain, 
			 INTERVAL_VECTOR & TheDomain_Parameter, 
			 int Nb_Points,
			 int Use_Solve,
			 int rand_max,
			 int Iteration_Geometry,
			 int Iteration_Polynom,
			 double Accuracy_Variable,
			 double Accuracy,
			 double Accuracy_Geometry,
			 double Accuracy_Polynom,
			 INTERVAL_VECTOR &Solution,
			 double *Seuil_First_Sol1,
			 int (* Solve_Poly)(double *, int *,double *), 
			 int (* Simp_Proc)(INTERVAL_VECTOR &),
			 int (* Simp_Proc_Pol)(INTERVAL_VECTOR &));

int ALIAS_Matrix_Void(INTERVAL_VECTOR &Box,INTERVAL_MATRIX &P);

INTERVAL_MATRIX ALIAS_Gradient_Void(int l1,int l2,INTERVAL_VECTOR &P);

int Kharitonov(int Degree,
	       INTERVAL_VECTOR (* TheCoeff)(double a,INTERVAL_VECTOR &), 
	       int (* Solve_Poly)(double *, int *,double *), 
	       INTERVAL_VECTOR &Input);

